### ISSUE TITLE
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by CunminZhao** [NarcissusEx/CuNeRF#8]
when i run the "bash example_train.sh"，it reports that"Traceback (most recent call last):
  File "/home/zhaolab/zcm/CuNeRF/run.py", line 137, in <module>
    globals()[args.mode](Cfg(args))
  File "/home/zhaolab/zcm/CuNeRF/run.py", line 57, in train
    for batch in cfg.trainloader:
  File "/home/zhaolab/miniconda3/envs/cunerf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/zhaolab/miniconda3/envs/cunerf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/zhaolab/miniconda3/envs/cunerf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/zhaolab/miniconda3/envs/cunerf/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 283, in __iter__
    for idx in self.sampler:
  File "/home/zhaolab/miniconda3/envs/cunerf/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 165, in __iter__
    yield from map(int, torch.randperm(n, generator=generator).numpy())
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
  0%|                                                | 1/200000 [00:00<?, ?it/s]"I'm not sure if this is an issue with your code or my problem.

**Comment by CunminZhao** [comment]
this error can be fixed by add "generator=torch.Generator(device='cuda')" to dataloader in src/config.py/line_65, thanks

**Comment by TFengXu** [comment]
src/config.py/line_65 ：setattr(self, f'{mode}loader', DataLoader(getattr(self, f'{mode}set'), **cfg[mode]))
where should I add "generator=torch.Generator(device='cuda')"

**Comment by renaissanceee** [comment]
try to add `generator=torch.Generator(device='cuda')` in your lib/python3.9/site-packages/torch/utils/data/sampler.py. I think around line 122.

**Comment by aruiplex** [comment]
Just modify the config.py line 65 to:

```
            setattr(self, f'{mode}loader', DataLoader(getattr(self, f'{mode}set'), **cfg[mode], generator=torch.Generator(device='cuda')))

```
